/**
 * An export profile builder will create the export profile necessary to export for a given environment.
 * Ex: an export profile builder will create an export profile for each density.
 */
export default class ExportProfileBuilder {

    /**
     * Returns the name of the export profile builder.
     * @return {string} name of the configurer.
     */
    getName() {
        return null;
    }

    /**
     * Create export profiles for the environment and add them to the output array.
     * @param baseExportProfile {ExportProfile}
     * @param outputName {string}
     * @param builderConfig {Object} JSON Object containing the configuration
     * @param exportProfiles {Array} Array where the export profiles generated by this builder will be added.
     */
    build(baseExportProfile, outputName, builderConfig, exportProfiles) {
        return Result.error(this.getName(), "build function must be implemented.");
    }

    /**
     * Update the default configuration of this builder.
     * @param defaultBuilderConfig {Object} JSON Object containing the default configuration.
     */
    updateDefaultConfig(defaultBuilderConfig) {

    }
}