import Result from "../utils/result";

/**
 * An export profile builder will create the export profile necessary to export for a given environment.
 * Ex: an export profile builder will create an export profile for each density.
 */
export default class ExportProfileBuilder {

    constructor() {
        this._baseOutputDir = null;
    }

    /**
     * Returns the name of the export profile builder.
     * @return {string} name of the configurer.
     */
    getName() {
        return null;
    }

    /**
     * Returns the base directory where all the images will be exported.
     * @return {File} base directory where all the images will be exported.
     */
    getBaseOutputDir() {
        return this._baseOutputDir;
    }

    /**
     * Set the base directory where all the images will be exported.
     * @param {File} baseOutputDir base directory where all the images will be exported.
     */
    setBaseOutputDir(baseOutputDir) {
        this._baseOutputDir = baseOutputDir;
    }

    /**
     * Create export profiles for the environment and add them to the output array.
     * @param {ExportProfile} baseExportProfile export profile containing all information about the image that will be exported.
     * @param {string} outputName name of the image that will be exported.
     * @param {File} outputDir base directory in which all images must be exported.
     * @param {Object} builderConfig JSON Object containing the configuration to use for this image.
     * @param {Array} exportProfiles Array where the export profiles generated by this builder will be added.
     * @return {Result} a result
     */
    build(baseExportProfile, builderConfig, exportProfiles) {
        return Result.error(this.getName(), "build function must be implemented.");
    }

    /**
     * Update the default configuration of this builder.
     * @param defaultBuilderConfig {Object} JSON Object containing the default configuration.
     */
    updateDefaultConfig(defaultBuilderConfig) {

    }
}